[metadata]
description-file = README.md

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.9
include_package_data = True

[options.packages.find]
where = src

[options.entry_points]
console_scripts =
    geojson-editor = geojson_editor.main:main

[easy_install]
zip_ok = False
